### ISSUE TITLE
Out-of-box experience

### ISSUE THREAD

**Issue by Habbie** [Hammerspoon/hammerspoon#13]
- [x] include core modules (#3)
- [x] include 3rd party modules (#4)
- [x] fix up accessibility (#8)
- [ ] default config?
- [ ] some wizard?
- [ ] write getting started doc
- [ ] Module discovery is hard - any ideas beyond the above?
