### ISSUE TITLE
Rewrite of hs.menubar

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1530]
As discussed in #1057, #914 and #1229 eventually it would be great to do a re-write of `hs.menubar`.

This should include:

- [ ] Rewriting `hs.menubar` to use the newer macOS `NSStatusItem` API (which should fix #914)
- [ ] Ability to "refresh" an already open menubar-menu (Discussed in #1229)
- [ ] Support for dragging and dropping to a menubar (Discussed in #1057)
- [ ] Support for attaching a `hs.webview` to a custom menubar (Discussed in #1057)

**Comment by asmagill** [comment]
* Remove priorities since they are no longer supported with 10.12+ -- #974

**Comment by latenitefilms** [comment]
@asmagill - I wonder if rather than using a `hs.webview` we could use a `hs._asm.guitk` as an attachment to a `hs.menubar` (i.e. to create an interface similar to Dropbox's system menubar item)?

**Comment by asmagill** [comment]
Ultimately, yes this is planned; don’t have an eta, though.

**Comment by asmagill** [comment]
FYI menubar rewrite in progress; will add with guitk in upcoming pull (needs some more testing and documentation)
