### ISSUE TITLE
Release 0.9.61

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#1631]
Let's play this game again @cmsj !

Here's my wish-list for **0.9.61** (or future releases):

---

**Issues I hope @asmagill will close:**
- [ ] Add Sample Mixed Lua/Objective-C Extension to Contribution Guide (issue #1345)
- [ ] Add [`hs._asm.guitk`](https://github.com/asmagill/hammerspoon_asm/tree/master/guitk) to Hammerspoon core (issue #1544, also fixes #1045, #1567, #914, #1229, #1057 and #974)
- [ ] Add [`hs._asm.preferences`](https://github.com/asmagill/hammerspoon_asm/tree/master/preferences) with `NSKeyedArchiver` to Hammerspoon core (issue #1498)
- [ ] Add [`hs._asm.touchbar`](https://github.com/asmagill/hammerspoon_asm/tree/master/touchbar) to Hammerspoon core (issue #1078)
- [ ] Add [`hs._asm.axuielement`](https://github.com/asmagill/hs._asm.axuielement) with Notifications to Hammerspoon core (issue #1630)
- [ ] Add [`hs._asm.undocumented.touchdevice`](https://github.com/asmagill/hammerspoon_asm.undocumented/tree/390ae06b18edd7604c51187262ede5c7e19944b7/touchdevice) - Support for Multi-Touch devices (issue #1623)
- [ ] Reading contents of a UTF-16 Little-Endian Encoded Text File? (issue #1452)
- [ ] Add `hs.bonjour` to Hammerspoon core (issue #1653)
- [ ] Add `hs.diskarbitration` to Hammerspoon core (issue #1654)

---

**Issues I hope @cmsj  will close:**
- [ ] Spoon lifecycle behaviour tweaks (issue #1480)
- [ ] Add `hs.styledtext` support to `hs.chooser` (issue #1624)

---

**Issues I hope SOMEONE will help close:**
- [ ] Add `hs.dialog.font` if someone can work out how to fix (issue #1528)
- [ ] `hs.keycodes` should be able to return a keycode map for the current layout (issue #1307)
- [ ] `ERROR: wfilter: app is not registered!` (issue #1551)
- [ ] Add callback option to `hs.mouse.scrollDirection()` (issue #1549)
- [ ] Detect external mouse? (issue #1587)
- [ ] Add Ability to add Custom Items to Dock Icon Contextual Menu (issue #1350)

---

**Issues I will attempt to close:**
- ~~[x] `hs.tangent` - Add support for Tangent Panels & iPad App (issue #1626)~~
- [ ] `hs.osc` - Add Extension for OSC Control (issue #1580)
- [ ] Localise Hammerspoon (issue #1357)

**Comment by asmagill** [comment]
If there is interest, I can also probably get these added within the next week or so:

- [ ] [hs._asm.bonjour](https://github.com/asmagill/hammerspoon_asm/tree/master/bonjour)
- [ ] [hs._asm.diskarbitration](https://github.com/asmagill/hammerspoon_asm/tree/master/diskarbitration)

**Comment by latenitefilms** [comment]
Ha! You're a mind reader @asmagill - we were literally chatting about the possibility of doing Bonjour with Hammerspoon the other week! Awesome!

**Comment by cmsj** [comment]
Closing this since we're up to 0.9.63 now, and I'm focusing almost exclusively on trying to get rid of bugs/crashers for now.

**Comment by latenitefilms** [comment]
@cmsj - No problemo! However, I'd still LOVE your help at some stage with #1624 and #1498.
