### ISSUE TITLE
Wishlist for 2020

### ISSUE THREAD

**Issue by latenitefilms** [Hammerspoon/hammerspoon#2262]
Just for fun, I thought I'd go back and review the things I'd love to see added and addressed in a future Hammerspoon release.

Here's a list of extensions I'd love to see added to Hammerspoon:

- [ ] **`hs.text` -  Module to handle different string encodings #2215**

- [ ] **`hs.axuielement` - Accessing Accessibility Objects with Hammerspoon #1630**
We've been using `hs._asm.axuielement` solidly for a few years now, and it's fricken awesome. It's been rock solid for us, and such an important and useful extension. I'd love to see this finally added to the Hammerspoon core, so that others can start using it, and also offer ideas, suggestions and pull requests.

- [ ] **`hs.preferences` - Property List Editor with NSKeyedArchiver support #1498**
There's quite a few issues and pull requests all tackling Property Lists & Defaults, so it would be great to finally consolidate and solve this feature requests for v1.0 as well. We currently use a mixture of `hs.plist`, `hs._asm.cfpreferences` and our own `cp.plist`. This would mean we could also finally finish up [`hs.notdisturbmode`](https://github.com/Hammerspoon/hammerspoon/pull/1706).

- [ ] **`hs.touchbar` - Add Extension for Touch Bar Support #1078**
We've been using `hs._asm.undocumented.touchbar` for ages now - it's also awesome and rock solid. I reckon this is probably ready to merge into Hammerspoon too? The only issue we've run into is that it [no longer works on the 16-inch MacBook Pro](https://github.com/asmagill/hammerspoon_asm.undocumented/issues/10), which I have no idea how to solve (especially as I don't personally own a 16-inch MacBook Pro).

In terms of other issues I'd love to tick off:

- [ ] Add "non activating" option to Console #2078
- [x] Update `hs.streamdeck` to support all the various hardware models #2102
- [ ] Crash - `hs.application:getMenus()` #2220
- [ ] [Catalina] Crash - `MJConsoleWindowController.m` line 74 #2206

**Comment by cmsj** [comment]
I'm planning to do a christmas release, but given where we are with the date, I'm not sure how much of this I'll get to :/
