### ISSUE TITLE
Proposed window/screen management extensions

### ISSUE THREAD

**Issue by lowne** [Hammerspoon/hammerspoon#341]
This is a meta-issue for tracking and discussing my proposed HS extensions (as per IRC convo).
Some sample usage with videos is at http://lowne.github.io/hammerspoon-extensions/
Code ~~is at https://github.com/lowne/hammerspoon-extensions (now outdated)~~  will be moved to the fork at https://github.com/lowne/hammerspoon as required.

---

List of proposed modules:
- [x] `hs.logger` - (merged. #346)
- [x] ~~`hs.delayed`~~ - (redundant, #347 and #530 - would be nice to have the `setNextTrigger(DISTANT_FUTURE)` trick somewhere in the wiki)
- [x] ~~`hs.screenwatcher` - standalone, a simple single instance wrapper around `hs.screen.watcher` and `hs.caffeinate.watcher`; naming not optimal; this module is not a strict requirement, but without it there would be a lot of repeated boilerplate and object duplicates at runtime in all the downstream modules~~ (probably redundant, but see #520)
- [x] `hs.grid` ~~`hs.grids`~~ - ~~requires screenwatcher; it might (or not) be possible to merge with `hs.grid`~~ (merged, #361 et al.)
- [x] `hs.window.filter` (merged, #374 et al.)
- [x] ~~`hs.windowwatcher`~~ merged into windowfilter
- [x] `hs.window.layout` - (wip, #550)
- [x] ~~`hs.windowtiling`~~ ~~will probably merge~~ sort of merged into window.layout
- [x] `hs.expose` (merged, #436)
- [ ] window-based "alt-tab" (will go into hs.expose)
- [ ] `hs.flux` (wip)

**Comment by cmsj** [comment]
@lowne Do we need to keep this issue open? You've covered pretty much all of it now, and I'm not paying a huge amount of attention to this tracking issue.
